//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DULIEUKTTV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesQLKTTV : DbContext
    {
        public EntitiesQLKTTV()
            : base("name=EntitiesQLKTTV")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanDo> BanDoes { get; set; }
        public virtual DbSet<BanTinDuBao> BanTinDuBaos { get; set; }
        public virtual DbSet<CapDo> CapDoes { get; set; }
        public virtual DbSet<DonViThoiGian> DonViThoiGians { get; set; }
        public virtual DbSet<DonViToChuc> DonViToChucs { get; set; }
        public virtual DbSet<DVHC_Huyen> DVHC_Huyen { get; set; }
        public virtual DbSet<DVHC_Tinh> DVHC_Tinh { get; set; }
        public virtual DbSet<DVHC_Xa> DVHC_Xa { get; set; }
        public virtual DbSet<File_DinhKem> File_DinhKem { get; set; }
        public virtual DbSet<KhuVuc> KhuVucs { get; set; }
        public virtual DbSet<KhuVucHanhChinh> KhuVucHanhChinhs { get; set; }
        public virtual DbSet<LoaiBanTin> LoaiBanTins { get; set; }
        public virtual DbSet<LoaiThienTai> LoaiThienTais { get; set; }
        public virtual DbSet<PhimHinhAnh> PhimHinhAnhs { get; set; }
        public virtual DbSet<TaiLieu> TaiLieux { get; set; }
        public virtual DbSet<TapTinDinhKem> TapTinDinhKems { get; set; }
        public virtual DbSet<ThanhPhanDuBao> ThanhPhanDuBaos { get; set; }
        public virtual DbSet<ThoiHanDuBao> ThoiHanDuBaos { get; set; }
        public virtual DbSet<ThongTinGiayPhep> ThongTinGiayPheps { get; set; }
    }
}
