//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DULIEUKTTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViToChuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonViToChuc()
        {
            this.ThongTinGiayPheps = new HashSet<ThongTinGiayPhep>();
            this.ThongTinGiayPheps1 = new HashSet<ThongTinGiayPhep>();
        }
    
        public int ID { get; set; }
        public string TenDonVi { get; set; }
        public string DiaChi { get; set; }
        public string MaSoThue { get; set; }
        public bool IsDeleted { get; set; }
        public string ToaDoX { get; set; }
        public string ToaDoY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinGiayPhep> ThongTinGiayPheps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinGiayPhep> ThongTinGiayPheps1 { get; set; }
    }
}
