//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DULIEUKTTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVHC_Huyen
    {
        public int MaHuyen { get; set; }
        public Nullable<int> MaTinh { get; set; }
        public string TenHuyen { get; set; }
    }
}
