//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DULIEUKTTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_DinhKem
    {
        public int ID { get; set; }
        public Nullable<int> ID_TaiLieu { get; set; }
        public Nullable<int> ID_GiayPhep { get; set; }
        public string Ten_FileDinhKem { get; set; }
        public string DuongDanURL { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string ViTri { get; set; }
        public Nullable<bool> IS_IMAGE { get; set; }
        public bool ISDELETE { get; set; }
    
        public virtual ThongTinGiayPhep ThongTinGiayPhep { get; set; }
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
