//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DULIEUKTTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiThienTai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiThienTai()
        {
            this.BanTinDuBaos = new HashSet<BanTinDuBao>();
        }
    
        public int ID { get; set; }
        public string TenLoaiThienTai { get; set; }
        public string MoTa { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanTinDuBao> BanTinDuBaos { get; set; }
    }
}
