//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DULIEUKTTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiLieu()
        {
            this.File_DinhKem = new HashSet<File_DinhKem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_HoSo { get; set; }
        public string TenTaiLieu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> ID_NguoiTao { get; set; }
        public Nullable<int> SoLanTai { get; set; }
        public Nullable<int> SoLanXem { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File_DinhKem> File_DinhKem { get; set; }
    }
}
