//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DULIEUKTTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiHanDuBao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThoiHanDuBao()
        {
            this.BanTinDuBaos = new HashSet<BanTinDuBao>();
        }
    
        public int ID { get; set; }
        public string TenThoiHanDuBao { get; set; }
        public Nullable<int> MaThanhPhanDuBao { get; set; }
        public Nullable<int> MaDonViThoiGian { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> TuThoiGian { get; set; }
        public Nullable<System.DateTime> DenThoiGian { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanTinDuBao> BanTinDuBaos { get; set; }
        public virtual DonViThoiGian DonViThoiGian { get; set; }
        public virtual ThanhPhanDuBao ThanhPhanDuBao { get; set; }
    }
}
