//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DULIEUKTTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinGiayPhep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinGiayPhep()
        {
            this.File_DinhKem = new HashSet<File_DinhKem>();
        }
    
        public int ID { get; set; }
        public string SoHieu { get; set; }
        public string Nam { get; set; }
        public Nullable<System.DateTime> NgayThang { get; set; }
        public string TenDonVi { get; set; }
        public string PhamViHoatDong { get; set; }
        public Nullable<int> DoiTuongCungCap { get; set; }
        public string GiaHan { get; set; }
        public Nullable<int> DonViKyXacNhan { get; set; }
        public Nullable<int> MaCapDoDuBao { get; set; }
        public string TrangThaiGiayPhep { get; set; }
        public string LyDoThuHoi { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CapDo CapDo { get; set; }
        public virtual DonViToChuc DonViToChuc { get; set; }
        public virtual DonViToChuc DonViToChuc1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File_DinhKem> File_DinhKem { get; set; }
    }
}
